### ISSUE TITLE
CurrentYear

### ISSUE THREAD

**Issue by horberlan** [BorjaRuizReverter/cyberfutureWebsite#11]
https://github.com/BorjaRuizReverter/cyberfutureWebsite/blob/e4e2ff7bc859e783a46a40d216e6e5bdaa9f0a92/src/components/footer.js#L61

```javascript
const CurrentYear = new Date().getFullYear();

**Comment by horberlan** [comment]
@BorjaRuizReverter

**Comment by BorjaRuizReverter** [comment]
Fixed!
